client/urls.py
from django.urls import path

from client.views import (
    ClientDetailView, 
    ClientList, 
    HomeView,
    ClientForm
)

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("clients/", ClientList.as_view(), name="client_list"),
    path("clients/<int:pk>/", ClientDetailView.as_view(), name="client_detail"),
    path("client/create/", ClientForm.as_view(), name='client_create_form')
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("client.urls")),
]

client/models.py
from django.db import models


class Client(models.Model):
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    id_number = models.CharField(max_length=250, unique=True)
    relation = models.ManyToManyField('client.Relationship')

class Relationship(models.Model):
    relation_type = (
        (0, "Husband"),
        (1, "Wife"),
        (2, "Mother"),
        (3, "Father"),
        (4, "Daughter"),
        (5, "Son")
    )
    address_type = models.IntegerField(
        choices=relation_type,
        default=0,
    )
    person = models.ForeignKey(Client, on_delete=models.PROTECT, related_name='relationships')
    relation = models.ForeignKey(Client, on_delete=models.PROTECT, related_name='reverse_relationships')

class Address(models.Model):
    client = models.ForeignKey(Client, on_delete=models.PROTECT)
    address_type_choices = (
        (0, "Physical"),
        (1, "Postal"),
    )
    address_type = models.IntegerField(
        choices=address_type_choices,
        default=0,
    )
    street = models.CharField(
        max_length=1024,
        blank=True,
        null=True,
    )
    street_number = models.CharField(
        max_length=10,
        blank=True,
        null=True,
    )
    unit_number = models.CharField(
        max_length=10,
        blank=True,
        null=True,
    )
    building = models.CharField(
        max_length=250,
        blank=True,
        null=True,
    )
    area = models.CharField(
        max_length=250,
        blank=True,
        null=True,
    )
    city = models.CharField(
        max_length=250,
        blank=True,
        null=True,
    )
    province = models.CharField(
        max_length=250,
        blank=True,
        null=True,
    )
    country = models.CharField(
        max_length=250,
        blank=True,
        null=True,
    )
    code = models.CharField(
        max_length=6,
        blank=True,
        null=True,
    )

client/forms/address_form.py
from django import forms
from client.models import Address, Client


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = [
            'address_type',
            'street',
            'street_number',
            'unit_number',
            'building' ,
            'area' ,
            'city',
            'province',
            'country',
            'code' ,
        ]
        widgets = {
            'address_type': forms.HiddenInput()
        }

client/forms/client_form.py
from django import forms

from client.models import Client, Address
from client.forms.address_form import AddressForm
from client.utils.id_verifier import IdVerifier


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ["first_name", "last_name", "id_number"]

    first_name = forms.CharField(label='First Name', max_length=250)
    last_name = forms.CharField(label='Last Name', max_length=250)
    id_number = forms.CharField(label='ID Number', max_length=20)

    def clean_id_number(self):
        id_verifier = IdVerifier()

        id_number = self.cleaned_data['id_number']
        if Client.objects.filter(id_number=id_number).exists():
            raise forms.ValidationError("ID number is not unique")
        
        if not id_verifier.is_valid_id_number(id_number):
            raise forms.ValidationError("Invalid ID number.")
        return id_number

client/forms/create_client_form.py
from django import forms

from client.models import Client, Address
from client.forms.address_form import AddressForm
from client.utils.id_verifier import IdVerifier


class CreateClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ["first_name", "last_name", "id_number"]

    first_name = forms.CharField(label='First Name', max_length=250)
    last_name = forms.CharField(label='Last Name', max_length=250)
    id_number = forms.CharField(label='ID Number', max_length=20)

    def clean_id_number(self):
        id_verifier = IdVerifier()

        id_number = self.cleaned_data['id_number']
        if Client.objects.filter(id_number=id_number).exists():
            raise forms.ValidationError("ID number is not unique")
        
        if not id_verifier.is_valid_id_number(id_number):
            raise forms.ValidationError("Invalid ID number.")
        return id_number

client/views.py
from django.views.generic import (
    DetailView, 
    ListView, 
    TemplateView,
    )
from django.forms import formset_factory

from multi_form_view import MultiModelFormView

# Forms
from client.forms.client_form import ClientForm
from client.forms.address_form import AddressForm

#Models
from client.models import Address, Client


class HomeView(TemplateView):
    template_name = "home.html"


class ClientList(ListView):
    model = Client
    template_name = "client_list.html"


class ClientDetailView(DetailView):
    model = Client
    template_name = "client_details.html"

    def get_context_data(self, **kwargs):
        context = super(ClientDetailView, self).get_context_data(**kwargs)
        context['address'] = Address.objects.all()
        return context

class ClientForm(MultiModelFormView):
    success_url ="/clients/"
    template_name = "client_create_form.html"

    def forms_valid(self, forms):
        # Make sure to save the client form first.
              
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['client'] =  ClientForm
        address_formset = formset_factory(AddressForm, extra=2, max_num=2)
        formset = address_formset()
        context['formset']= formset

        return context

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>Project</title>
  </head>
  <body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
	  <a class="navbar-brand" href="{% url 'home' %}">Project</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>
	  <div class="collapse navbar-collapse" id="navbarText">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item active">
		<a class="nav-link" href="{% url 'client_list' %}">Clients</a>
	      </li>
		  <li class="nav-item active">
			<a class="nav-link" href="{% url 'client_create_form' %}">Create Client</a>
		  </li>
	    </ul>
	  </div>
	</nav>

	<div class="container">
		{% block content %}
		{% endblock %}
	</div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

  </body>
</html>

templates/client_create_form.html
{% extends 'base.html' %}
{% block content %}
<div class="card m-3">
  <div class="card-header">
    Enter your credentials
  </div>
  <div class="card-body">
    <form class="form-horizontal" method="POST">
      {% csrf_token %}
      <div class="row">
        <div class="col-sm-6">
          <h3>Client Information</h3>
          <div>
            {{ forms.client.as_p }}
          </div>
        </div>
      </div>

      <div class="row">
        {% for address in formset %}
          {% if forloop.first %}
            <div class="col-sm-6">
              <h4>Physical Address</h4>
              <!-- <input type="hidden" name="address_type" id="id_address_type" value=""> -->
              {{ address.as_p }}
            </div>
          {% else %}
            <div class="col-sm-6">
              <h4>Postal Address</h4>
              <!-- <input type="text" name="address_type" id="id_address_type"> -->
              {{ address.as_p }}
            </div>
          {% endif %}
        {% endfor %}
      </div>



      <input type="submit" value="save">
    </form>
  </div>
</div>
{% endblock %}

templates/client_details.html
{% extends 'base.html' %}
{% block content %}
<div class="card m-3">
  <div class="card-header">
    Client
  </div>
  <div class="card-body">
	<p>First Name: {{ object.first_name }}</p>
	<p>Last Name: {{ object.last_name }}</p>
	<p>ID Number: {{ object.id_number }}</p>
  </div>
</div>
<div class="card m-3">
  <div class="card-header">
   Relationships
  </div>
  <div class="card-body">
  </div>
</div>
<div class="card m-3">
  <div class="card-header">
    Address
    {{ object.address }}
  </div>
  <div class="card-body">
  </div>  
</div>
{% endblock %}

templates/client_list.html
{% extends 'base.html' %}
{% block content %}
<div class="m-3">
	<h1>Client List</h1>
	<div class="input-group rounded mb-3">
	  <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search"
	    aria-describedby="search-addon" />
	</div>
	<table class="table table-bordered">
	  <thead>
	    <tr>
	      <th scope="col">ID</th>
	      <th scope="col">First Name</th>
	      <th scope="col">Last Name</th>
	      <th scope="col">ID Number</th>
	      <th scope="col">View Detail</th>
	    </tr>
	  </thead>
	  <tbody>
		{% for client in object_list %}
		    <tr>
		      <th scope="row">{{ client.pk }}</th>
		      <td>{{ client.first_name }}</td>
		      <td>{{ client.last_name }}</td>
		      <td>{{ client.id_number }}</td>
		      <td><a class="btn btn-primary" href="{% url 'client_detail' client.pk %}">View</a></td>
		    </tr>
		{% endfor %}
	  </tbody>
	</table>
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="m-3">
<h1>Project Info</h1>
<p>This repository includes a basic Django application which can be run using Docker Compose.</p>
<p>
	Some basic models, views and templates using Bootstrap have been created, and it is now up to you to expand on this with some additional functionality. It will be important to write unit tests to test any bit of functionality you have implemented.
</p>
<p>Once complete, commit your code to Github and share your project with us. You have 72 hours to complete as much as you are able to, and send your code back to us.</p>
<p>A list of functionality required includes:
<ul>
	<li>Validator which ensures the client's ID number is a valid South African ID number.</li>
	<li>Validator to ensure that a client with the same ID number doesn't already exist, notifying the user before the form is even submitted.</li>
	<li>Create a "New Client" form which allows you to add the client and address details at the same time and update both models. A client should have both a Physical and Postal address, unless the Postal address is the same as the Physical address.</li>
	<li>Create option to search for clients on the client list page, which updates as you type, but searches on the server side.</li>
	<li>Add a new "Relationship" Model which allows you to create relationship between clients (e.g Husband, Wife, Father, Daughter) and create a form to create these relationships, as well as a page to view them. A client cannot have a relationship with themself.</li>
</ul>
</p>
</div>
{% endblock %}